spring:
  thymeleaf:
    prefix: file://${user.dir}/src/main/resources/templates/
    cache: false

telegram:
  bot:
    username: make-your-own-bot
    token: get-your-own-token
#    proxy:
#      host: u0k12.tgproxy.me
#      port: 1080
#      username: telegram
#      password: telegram
