spring:
  freemarker:
    template-loader-path: ['file://${user.dir}/src/main/resources/templates/']
    cache: false

telegram:
  bot:
    username: make-your-own-bot
    token: get-your-own-token
    proxy:
      host: srv2.freetelegram.org
      port: 10000
      scheme: socks5
      username: freetelegram.org
      password: freetelegram.org

projects:
  test:
    telegram-chat-id: 'LTMwMTI0OTU2NQ=='
